title: KiRa-KiRa Sensation
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: You Know Who
  email: no@need

plugins:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

paginate_path: "/page:num"

paginate: 10

collections_dir: all_collections
collections:
  posts:
    output: true
  projects:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /:year/:month/:day/:title

exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
